### ISSUE TITLE
Office League- Sample data

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-office-league#190]

**Comment by aro** [comment]
We have a way to generate random team names, in random-names.js.
We need something similar for player names, and league names.

And ideally a way to generate random images (e.g. gravatar style) or import random images from some internet service.

An idea is to get the default icons for player and league, which are SVG, and generate random variations by changing the colors. This can easily be done with a search/replace pattern in the svg xml.

**Comment by GlennRicaud** [comment]
Thomas proposed to have superheroes as sample players. I found some lego superhero pictures under creative commons and imported them.
