### ISSUE TITLE
Office League - Create player form improvements

### ISSUE THREAD

**Issue by aro** [enonic/app-office-league#230]
- Set the fullname from the logged user display name (not the username)
- Restriction so username cannot have spaces
- Hide email field in create player form
- Set focus on username when page is loaded
- Align labels in create player form
- Show button/link with "Click to upload" instead of default player image
- Disable capitalize for username field (autocapitalize="none")

**Comment by aro** [comment]
All done, but iOS ignores the focus set on the input field (for "usability reasons" to avoid showing the screen keyboard).

The only way to do it is as a response to a page event, like click or touch on the page. But then there is not so much point, the user can just click on the input.

**Comment by sigdestad** [comment]
Ah, yes - focus only matters on desktop I guess :-)
‌‌

https://enonic.com <https://enonic.com/> - A web operating system for your sites and applications
