### ISSUE TITLE
Office League - Player selection UI improvements

### ISSUE THREAD

**Issue by aro** [enonic/app-office-league#248]
In the game player selection modal:
- Show max 3 players per row (it could be more on desktop view)
- Show name with ellipsis if too long
- Rounded images

**Comment by GlennRicaud** [comment]
On smallest screen (Iphone5), the width of the player icon container is 208px:
/3 blocks: 69.3
-padding of 2*2: 65

Images should be 64*64 width
 and border-radius of 32px
