### ISSUE TITLE
Office League - Player image fails to load in game-play

### ISSUE THREAD

**Issue by aro** [enonic/app-office-league#261]
The player image sometimes is not loaded when starting a game. 
It seems that it happens more often with svg. After refreshing the page it loads correctly.

**Comment by sigdestad** [comment]
+1 on this from me, it happens regularly when using jpegs for me.

**Comment by aro** [comment]
@sigdestad @mortyeriksen I made a change that will hopefully fix it. Let me know if you get the issue again. It's updated in officeleague.rocks
