### ISSUE TITLE
Office League - Check if game already started for the selected players

### ISSUE THREAD

**Issue by aro** [enonic/app-office-league#286]
When a game is started, check if there is already a game in progress for one of the players.
Give option to delete the other game, or continue playing the started game.

Use Owner property in game.

**Comment by carbonin** [comment]
This becomes a big issue when someone neglects to add the last goal to a game and navigates away from the field page. At that point (as far as I know) that game just sits in limbo forever.

**Comment by aro** [comment]
@carbonin We made an improvement. If you go away from the game, you can go back and select it (it appears in the league screen). If you are one of the players in the game, and the game was not completed, you are asked if you want to continue playing. Then you can either just finish the game, or delete it if you want.
