### ISSUE TITLE
Login page gets your gravatar, but then the character profile doesn't have it

### ISSUE THREAD

**Issue by Fryguy** [enonic/app-office-league#316]
When you create an account, your login page gets your gravatar (btw, I ❤️  the way it animates in when you type in your email address), but avatar for your account is only via upload, and doesn't have a gravatar option, nor does it default to your gravatar.

**Comment by aro** [comment]
Nice idea. We can start by fetching the gravatar automatically when the player is created. And maybe also add an option in the player profile page.

**Comment by aro** [comment]
When creating a new player it now sets the user Gravatar as image if found. Otherwise it takes the profile picture from the Identity provider (Gmail, Facebook).
Existing users are not updated.
