### ISSUE TITLE
Make points-per-game configurable

### ISSUE THREAD

**Issue by Fryguy** [enonic/app-office-league#317]
Our table has 5 points per side not 10 (Tornado table), so it would be cool if we could set the value at the start of a game.  Or perhaps, maybe we could set a default for our league, so any game within that league would default to that value.

I tried looking into changing this, but it's hardcoded in a number of places: e.g.
https://github.com/enonic/app-office-league/blob/9672b4237c85febf6f3ad8e38065ae343dd3758c/src/angular/app/services/ranking.service.ts

**Comment by aro** [comment]
There is more people asking for this. We have implemented it as configuration on the league (see #311) . 
It is basically done. We need to do a bit more testing and we will probably update the server the coming week.
Thanks for the feedback.

**Comment by Fryguy** [comment]
Ah, thanks...I saw the PR, but didn't realize it was going for the same goal.

I'll close this issue.

**Comment by aro** [comment]
Hi @Fryguy 

We have just updated officeleague.rocks with configuration for setting number of goals per game.
You can change it when you edit your league. You can set number of goals to win, and also by how many points difference it should be. Also whether or not team players switch position at half time, for 2 vs 2.

Let us know if everything works as expected when you try it.

**Comment by carbonin** [comment]
> Also whether or not team players switch position at half time, for 2 vs 2

I know I'm reusing an unrelated issue here, but this caught my eye.
Is this something that is tracked for any meaningful statistic? I don't see anything where it looks like it might apply ...

**Comment by aro** [comment]
At this moment it's only used for switching position of players in the play-game view. Just a visual thing.

The idea is to use it for statistics, since then we can know who was goalkeeper and who was attacker and extract some stats from data. But this has not been implemented yet. Probably won't be in the short term.
