### ISSUE TITLE
Resume game after leaving page

### ISSUE THREAD

**Issue by Fryguy** [enonic/app-office-league#319]
If you accidentally hit the browser back button or close your browser, and you are the one tallying the game, there is no way to go back and resume a game, or cancel the game.  It just gets stuck, and the only recourse is to delete the game.

**Comment by carbonin** [comment]
Think this is a duplicate of #286 right?

**Comment by Fryguy** [comment]
Yes, @aro's comment in #286 would solve this issue as well, so I'll close.
