### ISSUE TITLE
RFE - Should allow option for winning with 5 goals (and without the 2 point differential)

### ISSUE THREAD

**Issue by JPrause** [enonic/app-office-league#321]
Our games are during lunch break at work.
The games end when a player or team scores 5 goals.
This allows for faster games, and more people to play within lunch break.

To get around the current winning score of 10, we're scoring a goal as two goals in Office League.

cc: @carbonin @fryguy

**Comment by aro** [comment]
Hi

This was implemented and the server was updated yesterday. It needs to be configured on the league page.
So your league admin (bdunne or Fryguy) should go to the league page, click on Edit and change the settings for "Points to win" and "Minimum point difference to win".

See also #317

**Comment by JPrause** [comment]
Very Cool! I didn't see that @fryguy had already opened this same RFE a week ago. 
Thanks for implementing it!!
