### ISSUE TITLE
Office League - Push notifications not received

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-office-league#340]
From mer: The push notifications doesn't seem to work. Thomas has enabled and I tried to start a game.

**Comment by aro** [comment]
I've fixed an issue related to this.
Sometimes the new game event was received before the game node could be queried in ES, and the notification was skipped. It was timing dependant, that would explain why we saw it a bit randomly.

Hopefully it was the same reason why we have missed notifications before. Closing this issue.
