### ISSUE TITLE
App does not build, possible webpack AOT problem

### ISSUE THREAD

**Issue by diegopasten** [enonic/app-office-league#349]
This app does not build now.
Tried using local gradle (latest as of today) and found that the webpack AOT (js lazy loading) part of the build was failing. I disabled those parts of the build, and it starts nicely.

**Comment by alansemenov** [comment]
@GlennRicaud is it a known problem or something with Diego's local build?

**Comment by GlennRicaud** [comment]
No I don't think so. I think there is a problem when doing AOT compilation for Angular. I will assign it to  pmi
