### ISSUE TITLE
Upgrade app-office-league to be compatible with XP 7

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-office-league#352]
http://wiki.enonic.com/display/dev/7.0+app+upgrade+guide

**Comment by poi33** [comment]
Maybe change this into an epic ? 
Do not know how much work it would be to upgrade the office leage.

**Comment by sigdestad** [comment]
@poi33 is this task completed?

**Comment by poi33** [comment]
There is a working build on 7.0, but would not say its done. Since we need to put it up on qa and see if everything still works. 
Like the id provider login, creating and modifieng nodes etc.

**Comment by poi33** [comment]
After over a year this is finnaly done!
