### ISSUE TITLE
Installation of OL does not "work" anymore on chrome etc

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-office-league#416]
I do not get the install option on android, or the install icon on chrome for mac.

**Comment by poi33** [comment]
This should be fixed in the qa version now. [qa.officeleague.rocks/app](https://qa.officeleague.rocks/app) 

Workign in:
- android firefox mobile
- andorid chome mobile
- edge pc
- chrome pc 

Firefox pc does not support pwa installation atm.
