### ISSUE TITLE
Change the content type app to an actual webapp

### ISSUE THREAD

**Issue by poi33** [enonic/app-office-league#459]
Move the folder to the webapp location
Change assets to work in the new webapp structure
Change the assosiated webpack configuration to webapp structure

**Comment by poi33** [comment]
Seems like the assets where served straight from the build folder? 
Changing it to use lib-portal as described in my first webapp. Might need to change to lib static later.

**Comment by sigdestad** [comment]
I think you need to keep the same setup as this affects how headers and other assets are served. Using lib-portal will break this afaik.
