### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by geojohannes** [enonic/app-office-league#479]
Hi. Some of my colleagues and I are unable to reset our password. After clicking reset password, I never got an email.  I also tried to log on too many times because I couldn't reset my password, and it says that my user is blocked.

**Comment by poi33** [comment]
Thank you for reporting this problem geojohannes. 
I'll try to take a look at the mail service as soon as possible. 
Just tested it, and I also do not get any email when trying to reset the password.

**Comment by eithe** [comment]
Any updates on this @poi33?

**Comment by poi33** [comment]
I put this on high priority.. yet not given any time to work on it.
I'll try to take a look at this as soon as I'm done with my current assignment. This is not really acceptible to have down for such a long time.

**Comment by poi33** [comment]
I think i found the issue. 
I was able to create an account and ask for a password reset. Tell me if you still have issues.

**Comment by geojohannes** [comment]
I tried to reset the password on my current account, and I still don't get any email.

**Comment by poi33** [comment]
@eithe @geojohannes Could you try to reset your passwords now? We found the issue, but it might not be fixed yet. 
@geojohannes i send an email to verify your email, it was a test to see if the accounts and email system worked. No need to pay any attention to that email.

**Comment by geojohannes** [comment]
It worked now. Thanks!

However, I can't log on with the same password on my mobile. It says after trying with the same password "Unable to configure verification page."

I had the same bug before, that's what got me to reset the password in the first case. 

Do you want me to open a new issue?

**Comment by poi33** [comment]
Looks like this is an issue with third party cookies, and seems that iOS devices are more prone to this error. 
We would have bigger changes to the login system if this is to be prevented. 
If you have turned third party cookies off on your device, you can turn these on to avoid htis issue.

**Comment by geojohannes** [comment]
Thanks, that worked
