### ISSUE TITLE
Not working image set function

### ISSUE THREAD

**Issue by Bestils** [enonic/app-office-league#492]
Whenever i have tried to set image for team or player I got prompt with info: 
![image](https://user-images.githubusercontent.com/23175356/129915150-17ebae85-cc0e-48c8-a0da-e32594604f9f.png)
I have copied cURL and here is result from this try
`{
    "cause2": "java.io.IOException: Missing content for multipart request",
    "cause1": "org.eclipse.jetty.io.RuntimeIOException: java.io.IOException: Missing content for multipart request",
    "cause0": "javax.servlet.ServletException: org.eclipse.jetty.io.RuntimeIOException: java.io.IOException: Missing content for multipart request",
    "message": "javax.servlet.ServletException: org.eclipse.jetty.io.RuntimeIOException: java.io.IOException: Missing content for multipart request",
    "url": "/app/_/service/com.enonic.app.officeleague/set-image",
    "status": "500"
}`

**Comment by poi33** [comment]
Thanks for reporting this Bestils. 

Hmm 500 error on the image upload. 
What format is the image your are trying to upload?

**Comment by Bestils** [comment]
@poi33  all of them, png, jpg jpeg
