### ISSUE TITLE
Office League - UI - Labels and text overlap in form

### ISSUE THREAD

**Issue by aro** [enonic/app-office-league#81]
When the value of an input text is set from the controller, the text in the input field is displayed over the placeholder text (taken from the label).
This can be seen for example while editing a league.

![screen shot 2017-03-10 at 07 29 20](https://cloud.githubusercontent.com/assets/430739/23784692/b6533fba-0563-11e7-93f3-449766778d94.png)

There is a closed issue in Materialize, but some comments suggest the same issue when using it with Angular:
https://github.com/Dogfalo/materialize/issues/180

Try to find some kind of fix or workaround.

**Comment by pmi** [comment]
Can't seem to reproduce it, so leaving it for now

**Comment by LocDaiNguyen** [comment]
If you are using angular 2+ you can use ngClass to add the active class to the label. When property is loaded the active class gets added and moves up.

Works on chrome 56 / mac book pro 10.11.4 el capitan

    <input
      [ngModel]="user?.firstName"
      type="text"
      name="firstName"
      id="firstName"
      class="validate">
    <label [ngClass]="{'active': user?.firstName}" for="firstName">First Name</label>
